movies = [
  {
    id: "1",
    img: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1.png",
    title: "Interstellar",
    year: 2014,
    type: ["Adventure, Drama, Sci-Fi"],
    director: ["Jonathan Nolan", "Christopher Nolan"],
    genre: ["Adventure", "Drama", "Sci-Fi"],
    rated: "PG-13",
    released: "07 Nov 2014",
    boxoffice: "$188,020,017",
    runtime: "169 min",
    plot: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    imdbID: "tt0816692",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "73%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
  },
  {
    id: "2",
    img: "https://m.media-amazon.com/images/M/MV5BZTcxNzgzZjMtYzZiZC00MmE1LTg3MzQtZDAxMTYyZWE4MDNhL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1.png",
    title: "You've Got Mail",
    year: 1998,
    type: ["Comedy", "Drama", "Romance"],
    director: ["Miklós László", "Nora Ephron", "Delia Ephron"],
    genre: ["Comedy", "Drama", "Romance"],
    rated: "PG",
    released: "18 Dec 1998",
    boxoffice: "$115,821,495",
    runtime: "119 min",
    plot: "Book superstore magnate Joe Fox and independent book shop owner Kathleen Kelly fall in love in the anonymity of the Internet, both blissfully unaware that he's trying to put her out of business.",
    imdbID: "tt0128853",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "70%",
      },
      {
        Source: "Metacritic",
        Value: "57/100",
      },
    ],
  },
  {
    id: "3",
    img: "https://m.media-amazon.com/images/M/MV5BYTkxMDc2OTUtNjAyYi00NDUyLWE4OGMtODQwMjY5ZmRmOTMwXkEyXkFqcGdeQXVyMjM3NjM3Mg@@._V1.png",
    title: "The Crowded Room",
    year: 2023,
    type: ["Biography", "Crime", "Drama"],
    director: ["Akiva Goldsman", "Todd Graff"],
    genre: ["Biography", "Crime", "Drama"],
    rated: "TV-MA",
    released: "09 Jun 2023",
    runtime: "N/A ",
    plot: "In Manhattan in the summer of 1979, a young man is arrested for a shocking crime, and an unlikely investigator must solve the mystery behind it before the true criminal strikes again.",
    imdbID: "tt14417718",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
  },
  {
    id: "4",
    img: "https://m.media-amazon.com/images/M/MV5BMTUzNjE5ODYwN15BMl5BanBnXkFtZTgwMTY4MjQ1MTI@._V1._V1.png",
    title: "The Discovery",
    year: 2017,
    type: ["Drama", "Romance", "Sci-Fi"],
    director: ["Charlie McDowell", "Justin Lader"],
    genre: ["Drama", "Romance", "Sci-Fi"],
    rated: "TV-MA",
    released: "31 Mar 2017",
    runtime: "102 min",
    plot: "Two years after the afterlife is scientifically proven, a man attempts to help a young woman break away from her dark past.",
    imdbID: "tt5155780",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.2/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "46%",
      },
      {
        Source: "Metacritic",
        Value: "54/100",
      },
    ],
  },
  {
    id: "5",
    img: "https://m.media-amazon.com/images/M/MV5BZjdmZDlkMzItNTg0OS00MjAxLWE0ZTQtZjdhOWM1MTJkOTc0XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1.png",
    title: "Run",
    year: 2020,
    type: ["Mystery", "Thriller"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Mystery", "Thriller"],
    rated: "PG-13",
    released: "20 Nov 2020",
    runtime: "90 min",
    plot: "A homeschooled teenager begins to suspect her mother is keeping a dark secret from her.",
    imdbID: "tt8633478",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "89%",
      },
      {
        Source: "Metacritic",
        Value: "67/100",
      },
    ],
  },
  {
    id: "6",
    img: "https://m.media-amazon.com/images/M/MV5BNzI4MDMwMzUwNF5BMl5BanBnXkFtZTgwMDgyNzkyNzE@._V1.png",
    title: "How To Be Single",
    year: 2016,
    type: ["Comedy, Drama, Romance"],
    director: ["Abby Kohn", "Marc Silverstein", "Dana Fox"],
    genre: ["Comedy, Drama, Romance"],
    rated: "R",
    released: "12 Feb 2016",
    boxoffice: "$46,843,513",
    runtime: "110 min",
    plot: "A group of young adults navigate love and relationships in New York City.",
    imdbID: "tt1292566",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "46%",
      },
      {
        Source: "Metacritic",
        Value: "51/100",
      },
    ],
  },

  {
    id: "7",
    img: "https://m.media-amazon.com/images/M/MV5BZjQxOTY2MzYtZjhhNy00Y2ExLWJiMWYtYTNkMzA2ZTk5MDU4XkEyXkFqcGdeQXVyNTU5Mzk0NjE@._V1.png",
    title: "Our Friend",
    year: 2019,
    type: ["Drama", "Romance"],
    director: ["Brad Ingelsby", "Matthew Teague"],
    genre: ["Drama", "Romance"],
    rated: "R",
    released: "29 Jan 2021",
    boxoffice: "$663,725",
    runtime: "124 min",
    plot: "After receiving life-altering news, a couple finds unexpected support from their best friend, who puts his own life on hold and moves into their family home, bringing an impact much greater and more profound than anyone could have...",
    imdbID: "tt9608818",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "86%",
      },
      {
        Source: "Metacritic",
        Value: "57/100",
      },
    ],
  },
  {
    id: "8",
    img: "https://m.media-amazon.com/images/M/MV5BMTMzODg4MjU4OF5BMl5BanBnXkFtZTYwNDAzNTU3._V1.png",
    title: "The Painted Veil",
    year: 2006,
    type: ["Drama", "Romance"],
    director: ["Ron Nyswaner", "W. Somerset Maugham"],
    genre: ["Drama", "Romance"],
    rated: "PG-13",
    released: "19 Jan 2007",
    boxoffice: "$8,060,487",
    runtime: "125 min",
    plot: "A British medical doctor fights a cholera epidemic in a small Chinese village, while being trapped at home in a loveless marriage to an unfaithful wife.",
    imdbID: "tt0446755",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.4/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "74%",
      },
      {
        Source: "Metacritic",
        Value: "69/100",
      },
    ],
  },

  {
    id: "9",
    img: "https://m.media-amazon.com/images/M/MV5BNmQxZTNiODYtNzBhYy00MzVlLWJlN2UtNTc4YWZjMDIwMmEzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1.png",
    title: "The French Dispatch",
    year: 2021,
    type: ["Comedy", "Drama", "Romance"],
    director: ["Wes Anderson", "Roman Coppola", "Hugo Guinness"],
    genre: ["Comedy", "Drama", "Romance"],
    rated: "R",
    released: "22 Oct 2021",
    boxoffice: "$16,124,375",
    runtime: "107 min",
    plot: 'A love letter to journalists set in an outpost of an American newspaper in a fictional twentieth century French city that brings to life a collection of stories published in "The French Dispatch Magazine',
    imdbID: "tt8847712",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "75%",
      },
      {
        Source: "Metacritic",
        Value: "74/100",
      },
    ],
  },
  {
    id: "10",
    img: "https://m.media-amazon.com/images/M/MV5BMDJiZGE5NzYtZGU3Zi00NDQwLWFhMjAtNTM0MDM2ZTljMjAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1.png",
    title: "Ratched",
    year: "2020-",
    type: ["Crime, Drama, History"],
    director: ["Ryan Murphy", "Evan Romansky"],
    genre: ["Crime, Drama, History"],
    rated: "TV-MA",
    released: "18 Sep 2020",
    runtime: "N/A",
    plot: "In 1947, Mildred Ratched begins working as a nurse at a leading psychiatric hospital. But beneath her stylish exterior lurks a growing darkness.",
    imdbID: "tt7423538",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.3/10",
      },
    ],
  },
];
