movies = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1.png",
    title: "Interstellar",
    year: 2014,
    type: ["Adventure, Drama, Sci-Fi"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/M/MV5BZTcxNzgzZjMtYzZiZC00MmE1LTg3MzQtZDAxMTYyZWE4MDNhL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1.png",
    title: "You've Got Mail",
    year: 1998,
    type: ["Comedy", "Drama", "Romance"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/M/MV5BYTkxMDc2OTUtNjAyYi00NDUyLWE4OGMtODQwMjY5ZmRmOTMwXkEyXkFqcGdeQXVyMjM3NjM3Mg@@._V1.png",
    title: "The Crowded Room",
    year: 2023,
    type: ["Biography, Crime, Drama"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/M/MV5BMTUzNjE5ODYwN15BMl5BanBnXkFtZTgwMTY4MjQ1MTI@._V1._V1.png",
    title: "The Discovery",
    year: 2017,
    type: ["Drama, Romance, Sci-Fi"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/M/MV5BZjdmZDlkMzItNTg0OS00MjAxLWE0ZTQtZjdhOWM1MTJkOTc0XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1.png",
    title: "Run",
    year: 2020,
    type: ["Mystery, Thriller"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/M/MV5BNzI4MDMwMzUwNF5BMl5BanBnXkFtZTgwMDgyNzkyNzE@._V1.png",
    title: "How To Be Single",
    year: 2016,
    type: ["Comedy, Drama, Romance"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },

  {
    id: 7,
    img: "https://m.media-amazon.com/images/M/MV5BZjQxOTY2MzYtZjhhNy00Y2ExLWJiMWYtYTNkMzA2ZTk5MDU4XkEyXkFqcGdeQXVyNTU5Mzk0NjE@._V1.png",
    title: "Our Friend",
    year: 2019,
    type: ["Drama", "Romance"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 8,
    img: "https://m.media-amazon.com/images/M/MV5BMTMzODg4MjU4OF5BMl5BanBnXkFtZTYwNDAzNTU3._V1.png",
    title: "The Painted Veil",
    year: 2006,
    type: ["Drama", "Romance"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },

  {
    id: 9,
    img: "https://m.media-amazon.com/images/M/MV5BNmQxZTNiODYtNzBhYy00MzVlLWJlN2UtNTc4YWZjMDIwMmEzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1.png",
    title: "The French Dispatch",
    year: 2021,
    type: ["Comedy", "Drama", "Romance"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
  {
    id: 10,
    img: "https://m.media-amazon.com/images/M/MV5BMDJiZGE5NzYtZGU3Zi00NDQwLWFhMjAtNTM0MDM2ZTljMjAzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1.png",
    title: "Ratched",
    year: 2020,
    type: ["Crime, Drama, History"],
    director: ["Aaron Horvath", "Michael Jelenic", "Pierre Leduc"],
    genre: ["Animation", "Adventure", "Comedy"],
    rated: "PG",
    released: "05 Apr 2023",
    boxoffice: "$574,223,720",
    runtime: "92 min",
    plot: "A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "46/100",
      },
    ],
  },
];
